### ISSUE TITLE
Values for Kustomize?

### ISSUE THREAD

**Issue by burakbengi** [catenax-ng/devops-apps#1]
Hi,

I was looking the last merge below and would ask how the `.Values` can be added in a secure way? Shouldn't we have first:
1. Helm chart (instead of Kustomize)
2. Values.yaml and also
3. a working Vault 
for below changes to work?

Can we add these in a branch before merging it forcefully into main?
https://github.com/catenax-ng/devops-apps/blob/177d7b72a60353cfbedae8a3665d871fd10e3df3/argocd/github-oauth.yaml#L14-L16

Thx!

**Comment by ricogu** [comment]
1. argoCD support both helm and Kustomize, so for each individual app, I dont mind if it is installed by helm or kustomize
2. Values is available: https://github.com/catenax-ng/devops-apps/blob/main/apps/values.yaml, there is a little bit if trick here which we can clarify it in a call
3. yes, working vault or the github secret is also fine right?

**Comment by ricogu** [comment]
regarding the git flow, i think we should mention it in daily

**Comment by sTb1337** [comment]
As of now, I am not aware on how to store/inject confidential information from a vault in this Argo CD setup. 
Any idear @Siegfriedk?

**Comment by Siegfriedk** [comment]
@sTb1337 @ricogu & @burakbengi do we still need this issue? We introduced in our current sprint the vault plugin.

If not, pls close this issue.
